'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace who
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PeopleStoreSoap", [Namespace]:="http://who/")>  _
    Partial Public Class PeopleStore
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private FindPeopleByQueryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindPeopleByFuzzyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindPersonByAliasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindPeopleByAliasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindPeopleByEmployeeIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindPersonContextWithPeersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FindPersonContextByAliasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTagCompletionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUnderOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSearchCompletionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSearchCompletionsByAliasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSearchAddinCompletionsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Headtrax.My.MySettings.Default.Headtrax_who_PeopleStore
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event FindPeopleByQueryCompleted As FindPeopleByQueryCompletedEventHandler
        
        '''<remarks/>
        Public Event FindPeopleByFuzzyCompleted As FindPeopleByFuzzyCompletedEventHandler
        
        '''<remarks/>
        Public Event FindPersonByAliasCompleted As FindPersonByAliasCompletedEventHandler
        
        '''<remarks/>
        Public Event FindPeopleByAliasCompleted As FindPeopleByAliasCompletedEventHandler
        
        '''<remarks/>
        Public Event FindPeopleByEmployeeIdCompleted As FindPeopleByEmployeeIdCompletedEventHandler
        
        '''<remarks/>
        Public Event FindPersonContextWithPeersCompleted As FindPersonContextWithPeersCompletedEventHandler
        
        '''<remarks/>
        Public Event FindPersonContextByAliasCompleted As FindPersonContextByAliasCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTagCompletionsCompleted As GetTagCompletionsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUnderCompleted As GetUnderCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSearchCompletionsCompleted As GetSearchCompletionsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSearchCompletionsByAliasCompleted As GetSearchCompletionsByAliasCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSearchAddinCompletionsCompleted As GetSearchAddinCompletionsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPeopleByQuery", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPeopleByQuery(ByVal query As String, ByVal count As Integer) As Person()
            Dim results() As Object = Me.Invoke("FindPeopleByQuery", New Object() {query, count})
            Return CType(results(0),Person())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByQueryAsync(ByVal query As String, ByVal count As Integer)
            Me.FindPeopleByQueryAsync(query, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByQueryAsync(ByVal query As String, ByVal count As Integer, ByVal userState As Object)
            If (Me.FindPeopleByQueryOperationCompleted Is Nothing) Then
                Me.FindPeopleByQueryOperationCompleted = AddressOf Me.OnFindPeopleByQueryOperationCompleted
            End If
            Me.InvokeAsync("FindPeopleByQuery", New Object() {query, count}, Me.FindPeopleByQueryOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPeopleByQueryOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPeopleByQueryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPeopleByQueryCompleted(Me, New FindPeopleByQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPeopleByFuzzy", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPeopleByFuzzy(ByVal fuzzy As String) As Person()
            Dim results() As Object = Me.Invoke("FindPeopleByFuzzy", New Object() {fuzzy})
            Return CType(results(0),Person())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByFuzzyAsync(ByVal fuzzy As String)
            Me.FindPeopleByFuzzyAsync(fuzzy, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByFuzzyAsync(ByVal fuzzy As String, ByVal userState As Object)
            If (Me.FindPeopleByFuzzyOperationCompleted Is Nothing) Then
                Me.FindPeopleByFuzzyOperationCompleted = AddressOf Me.OnFindPeopleByFuzzyOperationCompleted
            End If
            Me.InvokeAsync("FindPeopleByFuzzy", New Object() {fuzzy}, Me.FindPeopleByFuzzyOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPeopleByFuzzyOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPeopleByFuzzyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPeopleByFuzzyCompleted(Me, New FindPeopleByFuzzyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPersonByAlias", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPersonByAlias(ByVal [alias] As String) As Person
            Dim results() As Object = Me.Invoke("FindPersonByAlias", New Object() {[alias]})
            Return CType(results(0),Person)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPersonByAliasAsync(ByVal [alias] As String)
            Me.FindPersonByAliasAsync([alias], Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPersonByAliasAsync(ByVal [alias] As String, ByVal userState As Object)
            If (Me.FindPersonByAliasOperationCompleted Is Nothing) Then
                Me.FindPersonByAliasOperationCompleted = AddressOf Me.OnFindPersonByAliasOperationCompleted
            End If
            Me.InvokeAsync("FindPersonByAlias", New Object() {[alias]}, Me.FindPersonByAliasOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPersonByAliasOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPersonByAliasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPersonByAliasCompleted(Me, New FindPersonByAliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPeopleByAlias", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPeopleByAlias(ByVal aliases() As String) As Person()
            Dim results() As Object = Me.Invoke("FindPeopleByAlias", New Object() {aliases})
            Return CType(results(0),Person())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByAliasAsync(ByVal aliases() As String)
            Me.FindPeopleByAliasAsync(aliases, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByAliasAsync(ByVal aliases() As String, ByVal userState As Object)
            If (Me.FindPeopleByAliasOperationCompleted Is Nothing) Then
                Me.FindPeopleByAliasOperationCompleted = AddressOf Me.OnFindPeopleByAliasOperationCompleted
            End If
            Me.InvokeAsync("FindPeopleByAlias", New Object() {aliases}, Me.FindPeopleByAliasOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPeopleByAliasOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPeopleByAliasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPeopleByAliasCompleted(Me, New FindPeopleByAliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPeopleByEmployeeId", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPeopleByEmployeeId(ByVal employeeIds() As Integer) As Person()
            Dim results() As Object = Me.Invoke("FindPeopleByEmployeeId", New Object() {employeeIds})
            Return CType(results(0),Person())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByEmployeeIdAsync(ByVal employeeIds() As Integer)
            Me.FindPeopleByEmployeeIdAsync(employeeIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPeopleByEmployeeIdAsync(ByVal employeeIds() As Integer, ByVal userState As Object)
            If (Me.FindPeopleByEmployeeIdOperationCompleted Is Nothing) Then
                Me.FindPeopleByEmployeeIdOperationCompleted = AddressOf Me.OnFindPeopleByEmployeeIdOperationCompleted
            End If
            Me.InvokeAsync("FindPeopleByEmployeeId", New Object() {employeeIds}, Me.FindPeopleByEmployeeIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPeopleByEmployeeIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPeopleByEmployeeIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPeopleByEmployeeIdCompleted(Me, New FindPeopleByEmployeeIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPersonContextWithPeers", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPersonContextWithPeers(ByVal [alias] As String) As PersonContextWithPeers
            Dim results() As Object = Me.Invoke("FindPersonContextWithPeers", New Object() {[alias]})
            Return CType(results(0),PersonContextWithPeers)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPersonContextWithPeersAsync(ByVal [alias] As String)
            Me.FindPersonContextWithPeersAsync([alias], Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPersonContextWithPeersAsync(ByVal [alias] As String, ByVal userState As Object)
            If (Me.FindPersonContextWithPeersOperationCompleted Is Nothing) Then
                Me.FindPersonContextWithPeersOperationCompleted = AddressOf Me.OnFindPersonContextWithPeersOperationCompleted
            End If
            Me.InvokeAsync("FindPersonContextWithPeers", New Object() {[alias]}, Me.FindPersonContextWithPeersOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPersonContextWithPeersOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPersonContextWithPeersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPersonContextWithPeersCompleted(Me, New FindPersonContextWithPeersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/FindPersonContextByAlias", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FindPersonContextByAlias(ByVal [alias] As String) As PersonContext
            Dim results() As Object = Me.Invoke("FindPersonContextByAlias", New Object() {[alias]})
            Return CType(results(0),PersonContext)
        End Function
        
        '''<remarks/>
        Public Overloads Sub FindPersonContextByAliasAsync(ByVal [alias] As String)
            Me.FindPersonContextByAliasAsync([alias], Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FindPersonContextByAliasAsync(ByVal [alias] As String, ByVal userState As Object)
            If (Me.FindPersonContextByAliasOperationCompleted Is Nothing) Then
                Me.FindPersonContextByAliasOperationCompleted = AddressOf Me.OnFindPersonContextByAliasOperationCompleted
            End If
            Me.InvokeAsync("FindPersonContextByAlias", New Object() {[alias]}, Me.FindPersonContextByAliasOperationCompleted, userState)
        End Sub
        
        Private Sub OnFindPersonContextByAliasOperationCompleted(ByVal arg As Object)
            If (Not (Me.FindPersonContextByAliasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FindPersonContextByAliasCompleted(Me, New FindPersonContextByAliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/GetTagCompletions", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTagCompletions(ByVal prefixText As String, ByVal count As Integer) As String()
            Dim results() As Object = Me.Invoke("GetTagCompletions", New Object() {prefixText, count})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTagCompletionsAsync(ByVal prefixText As String, ByVal count As Integer)
            Me.GetTagCompletionsAsync(prefixText, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTagCompletionsAsync(ByVal prefixText As String, ByVal count As Integer, ByVal userState As Object)
            If (Me.GetTagCompletionsOperationCompleted Is Nothing) Then
                Me.GetTagCompletionsOperationCompleted = AddressOf Me.OnGetTagCompletionsOperationCompleted
            End If
            Me.InvokeAsync("GetTagCompletions", New Object() {prefixText, count}, Me.GetTagCompletionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTagCompletionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTagCompletionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTagCompletionsCompleted(Me, New GetTagCompletionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/GetUnder", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUnder(ByVal [alias] As String) As Person()
            Dim results() As Object = Me.Invoke("GetUnder", New Object() {[alias]})
            Return CType(results(0),Person())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUnderAsync(ByVal [alias] As String)
            Me.GetUnderAsync([alias], Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUnderAsync(ByVal [alias] As String, ByVal userState As Object)
            If (Me.GetUnderOperationCompleted Is Nothing) Then
                Me.GetUnderOperationCompleted = AddressOf Me.OnGetUnderOperationCompleted
            End If
            Me.InvokeAsync("GetUnder", New Object() {[alias]}, Me.GetUnderOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUnderOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUnderCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUnderCompleted(Me, New GetUnderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/GetSearchCompletions", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSearchCompletions(ByVal prefixText As String, ByVal count As Integer) As String()
            Dim results() As Object = Me.Invoke("GetSearchCompletions", New Object() {prefixText, count})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSearchCompletionsAsync(ByVal prefixText As String, ByVal count As Integer)
            Me.GetSearchCompletionsAsync(prefixText, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSearchCompletionsAsync(ByVal prefixText As String, ByVal count As Integer, ByVal userState As Object)
            If (Me.GetSearchCompletionsOperationCompleted Is Nothing) Then
                Me.GetSearchCompletionsOperationCompleted = AddressOf Me.OnGetSearchCompletionsOperationCompleted
            End If
            Me.InvokeAsync("GetSearchCompletions", New Object() {prefixText, count}, Me.GetSearchCompletionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSearchCompletionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSearchCompletionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSearchCompletionsCompleted(Me, New GetSearchCompletionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/GetSearchCompletionsByAlias", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSearchCompletionsByAlias(ByVal prefixText As String, ByVal count As Integer) As String()
            Dim results() As Object = Me.Invoke("GetSearchCompletionsByAlias", New Object() {prefixText, count})
            Return CType(results(0),String())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSearchCompletionsByAliasAsync(ByVal prefixText As String, ByVal count As Integer)
            Me.GetSearchCompletionsByAliasAsync(prefixText, count, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSearchCompletionsByAliasAsync(ByVal prefixText As String, ByVal count As Integer, ByVal userState As Object)
            If (Me.GetSearchCompletionsByAliasOperationCompleted Is Nothing) Then
                Me.GetSearchCompletionsByAliasOperationCompleted = AddressOf Me.OnGetSearchCompletionsByAliasOperationCompleted
            End If
            Me.InvokeAsync("GetSearchCompletionsByAlias", New Object() {prefixText, count}, Me.GetSearchCompletionsByAliasOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSearchCompletionsByAliasOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSearchCompletionsByAliasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSearchCompletionsByAliasCompleted(Me, New GetSearchCompletionsByAliasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://who/GetSearchAddinCompletions", RequestNamespace:="http://who/", ResponseNamespace:="http://who/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSearchAddinCompletions(ByVal prefixText As String) As <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://schemas.microsoft.com/Search/2008/suggestions", IsNullable:=true)> SearchSuggestion
            Dim results() As Object = Me.Invoke("GetSearchAddinCompletions", New Object() {prefixText})
            Return CType(results(0),SearchSuggestion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSearchAddinCompletionsAsync(ByVal prefixText As String)
            Me.GetSearchAddinCompletionsAsync(prefixText, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSearchAddinCompletionsAsync(ByVal prefixText As String, ByVal userState As Object)
            If (Me.GetSearchAddinCompletionsOperationCompleted Is Nothing) Then
                Me.GetSearchAddinCompletionsOperationCompleted = AddressOf Me.OnGetSearchAddinCompletionsOperationCompleted
            End If
            Me.InvokeAsync("GetSearchAddinCompletions", New Object() {prefixText}, Me.GetSearchAddinCompletionsOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSearchAddinCompletionsOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSearchAddinCompletionsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSearchAddinCompletionsCompleted(Me, New GetSearchAddinCompletionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://who/")>  _
    Partial Public Class Person
        
        Private positionNumberField As Integer
        
        Private requestionIdField As String
        
        Private managerPositionNumberField As Integer
        
        Private approvedIndField As String
        
        Private openPositionSubGroupCodeField As String
        
        Private isPartOfOrgTreeField As Boolean
        
        Private nameField As String
        
        Private aliasField As String
        
        Private samAccountNameField As String
        
        Private titleField As String
        
        Private officeField As String
        
        Private telephoneField As String
        
        Private departmentField As String
        
        Private orgDepthField As Integer
        
        Private fullTimeReportsField As Integer
        
        Private vendorReportsField As Integer
        
        Private employeeIdField As Integer
        
        Private positionClassCodeField As String
        
        Private managerEmployeeIdField As System.Nullable(Of Integer)
        
        Private managerEmployeeIdFieldSpecified As Boolean
        
        Private openPositionVendorField As Boolean
        
        Private openPositionInternField As Boolean
        
        Private managerFullNameField As String
        
        Private agencyTempReportsField As Integer
        
        Private vendorWorkerReportsField As Integer
        
        Private businessGuestReportsField As Integer
        
        Private internReportsField As Integer
        
        Private jointVentureReportsField As Integer
        
        Private openEmployeeReportsField As Integer
        
        Private openInternReportsField As Integer
        
        Private imageLinkField As String
        
        Private personLinkField As String
        
        Private organizationLinkField As String
        
        Private isvendorField As Boolean
        
        '''<remarks/>
        Public Property PositionNumber() As Integer
            Get
                Return Me.positionNumberField
            End Get
            Set
                Me.positionNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequestionId() As String
            Get
                Return Me.requestionIdField
            End Get
            Set
                Me.requestionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ManagerPositionNumber() As Integer
            Get
                Return Me.managerPositionNumberField
            End Get
            Set
                Me.managerPositionNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApprovedInd() As String
            Get
                Return Me.approvedIndField
            End Get
            Set
                Me.approvedIndField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenPositionSubGroupCode() As String
            Get
                Return Me.openPositionSubGroupCodeField
            End Get
            Set
                Me.openPositionSubGroupCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsPartOfOrgTree() As Boolean
            Get
                Return Me.isPartOfOrgTreeField
            End Get
            Set
                Me.isPartOfOrgTreeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Alias]() As String
            Get
                Return Me.aliasField
            End Get
            Set
                Me.aliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SamAccountName() As String
            Get
                Return Me.samAccountNameField
            End Get
            Set
                Me.samAccountNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Office() As String
            Get
                Return Me.officeField
            End Get
            Set
                Me.officeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Telephone() As String
            Get
                Return Me.telephoneField
            End Get
            Set
                Me.telephoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrgDepth() As Integer
            Get
                Return Me.orgDepthField
            End Get
            Set
                Me.orgDepthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FullTimeReports() As Integer
            Get
                Return Me.fullTimeReportsField
            End Get
            Set
                Me.fullTimeReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VendorReports() As Integer
            Get
                Return Me.vendorReportsField
            End Get
            Set
                Me.vendorReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeId() As Integer
            Get
                Return Me.employeeIdField
            End Get
            Set
                Me.employeeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PositionClassCode() As String
            Get
                Return Me.positionClassCodeField
            End Get
            Set
                Me.positionClassCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ManagerEmployeeId() As System.Nullable(Of Integer)
            Get
                Return Me.managerEmployeeIdField
            End Get
            Set
                Me.managerEmployeeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ManagerEmployeeIdSpecified() As Boolean
            Get
                Return Me.managerEmployeeIdFieldSpecified
            End Get
            Set
                Me.managerEmployeeIdFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenPositionVendor() As Boolean
            Get
                Return Me.openPositionVendorField
            End Get
            Set
                Me.openPositionVendorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenPositionIntern() As Boolean
            Get
                Return Me.openPositionInternField
            End Get
            Set
                Me.openPositionInternField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ManagerFullName() As String
            Get
                Return Me.managerFullNameField
            End Get
            Set
                Me.managerFullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AgencyTempReports() As Integer
            Get
                Return Me.agencyTempReportsField
            End Get
            Set
                Me.agencyTempReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VendorWorkerReports() As Integer
            Get
                Return Me.vendorWorkerReportsField
            End Get
            Set
                Me.vendorWorkerReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BusinessGuestReports() As Integer
            Get
                Return Me.businessGuestReportsField
            End Get
            Set
                Me.businessGuestReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InternReports() As Integer
            Get
                Return Me.internReportsField
            End Get
            Set
                Me.internReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property JointVentureReports() As Integer
            Get
                Return Me.jointVentureReportsField
            End Get
            Set
                Me.jointVentureReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenEmployeeReports() As Integer
            Get
                Return Me.openEmployeeReportsField
            End Get
            Set
                Me.openEmployeeReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OpenInternReports() As Integer
            Get
                Return Me.openInternReportsField
            End Get
            Set
                Me.openInternReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageLink() As String
            Get
                Return Me.imageLinkField
            End Get
            Set
                Me.imageLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonLink() As String
            Get
                Return Me.personLinkField
            End Get
            Set
                Me.personLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrganizationLink() As String
            Get
                Return Me.organizationLinkField
            End Get
            Set
                Me.organizationLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property isvendor() As Boolean
            Get
                Return Me.isvendorField
            End Get
            Set
                Me.isvendorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/Search/2008/suggestions")>  _
    Partial Public Class Image
        
        Private sourceField As String
        
        Private widthField As String
        
        Private heightField As String
        
        Private alignField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property source() As String
            Get
                Return Me.sourceField
            End Get
            Set
                Me.sourceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property width() As String
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property height() As String
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property align() As String
            Get
                Return Me.alignField
            End Get
            Set
                Me.alignField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/Search/2008/suggestions")>  _
    Partial Public Class Item
        
        Private textField As String
        
        Private descriptionField As String
        
        Private imageField As Image
        
        Private urlField As String
        
        '''<remarks/>
        Public Property Text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Image() As Image
            Get
                Return Me.imageField
            End Get
            Set
                Me.imageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.microsoft.com/Search/2008/suggestions")>  _
    Partial Public Class SearchSuggestion
        
        Private queryField As String
        
        Private sectionField() As Item
        
        '''<remarks/>
        Public Property Query() As String
            Get
                Return Me.queryField
            End Get
            Set
                Me.queryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Section() As Item()
            Get
                Return Me.sectionField
            End Get
            Set
                Me.sectionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://who/")>  _
    Partial Public Class DirectData
        
        Private fullNameField As String
        
        Private titleField As String
        
        Private employeeIdField As Integer
        
        Private officeField As String
        
        Private locationField As String
        
        Private vendorField As Boolean
        
        Private totalReportsField As System.Nullable(Of Integer)
        
        Private totalOpenReportsField As System.Nullable(Of Integer)
        
        Private nestedSetLeftField As Integer
        
        Private nestedSetRightField As Integer
        
        Private treeDepthField As Byte
        
        Private aliasField As String
        
        Private positionNumberField As Integer
        
        Private requisitionAliasField As String
        
        Private fullTimeReportsField As Integer
        
        Private agencyTempField As Boolean
        
        Private vendorWorkerField As Boolean
        
        Private businessGuestField As Boolean
        
        Private internField As Boolean
        
        Private jointVentureEmpField As Boolean
        
        Private departmentField As String
        
        Private deptNicknameField As String
        
        Private keywordsField As String
        
        Private ownedDLsField As String
        
        Private tagsListField As String
        
        Private pMRollupCountField As Integer
        
        Private devRollupCountField As Integer
        
        Private testRollupCountField As Integer
        
        Private otherRollupCountField As Integer
        
        Private isOpenPositionField As System.Nullable(Of Boolean)
        
        Private approvedIndField As String
        
        Private imageLinkField As String
        
        Private personLinkField As String
        
        Private organizationLinkField As String
        
        '''<remarks/>
        Public Property FullName() As String
            Get
                Return Me.fullNameField
            End Get
            Set
                Me.fullNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EmployeeId() As Integer
            Get
                Return Me.employeeIdField
            End Get
            Set
                Me.employeeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Office() As String
            Get
                Return Me.officeField
            End Get
            Set
                Me.officeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Location() As String
            Get
                Return Me.locationField
            End Get
            Set
                Me.locationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vendor() As Boolean
            Get
                Return Me.vendorField
            End Get
            Set
                Me.vendorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalReports() As System.Nullable(Of Integer)
            Get
                Return Me.totalReportsField
            End Get
            Set
                Me.totalReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property TotalOpenReports() As System.Nullable(Of Integer)
            Get
                Return Me.totalOpenReportsField
            End Get
            Set
                Me.totalOpenReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NestedSetLeft() As Integer
            Get
                Return Me.nestedSetLeftField
            End Get
            Set
                Me.nestedSetLeftField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NestedSetRight() As Integer
            Get
                Return Me.nestedSetRightField
            End Get
            Set
                Me.nestedSetRightField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TreeDepth() As Byte
            Get
                Return Me.treeDepthField
            End Get
            Set
                Me.treeDepthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [Alias]() As String
            Get
                Return Me.aliasField
            End Get
            Set
                Me.aliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PositionNumber() As Integer
            Get
                Return Me.positionNumberField
            End Get
            Set
                Me.positionNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property RequisitionAlias() As String
            Get
                Return Me.requisitionAliasField
            End Get
            Set
                Me.requisitionAliasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FullTimeReports() As Integer
            Get
                Return Me.fullTimeReportsField
            End Get
            Set
                Me.fullTimeReportsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AgencyTemp() As Boolean
            Get
                Return Me.agencyTempField
            End Get
            Set
                Me.agencyTempField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VendorWorker() As Boolean
            Get
                Return Me.vendorWorkerField
            End Get
            Set
                Me.vendorWorkerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BusinessGuest() As Boolean
            Get
                Return Me.businessGuestField
            End Get
            Set
                Me.businessGuestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Intern() As Boolean
            Get
                Return Me.internField
            End Get
            Set
                Me.internField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property JointVentureEmp() As Boolean
            Get
                Return Me.jointVentureEmpField
            End Get
            Set
                Me.jointVentureEmpField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Department() As String
            Get
                Return Me.departmentField
            End Get
            Set
                Me.departmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DeptNickname() As String
            Get
                Return Me.deptNicknameField
            End Get
            Set
                Me.deptNicknameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Keywords() As String
            Get
                Return Me.keywordsField
            End Get
            Set
                Me.keywordsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OwnedDLs() As String
            Get
                Return Me.ownedDLsField
            End Get
            Set
                Me.ownedDLsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TagsList() As String
            Get
                Return Me.tagsListField
            End Get
            Set
                Me.tagsListField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PMRollupCount() As Integer
            Get
                Return Me.pMRollupCountField
            End Get
            Set
                Me.pMRollupCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DevRollupCount() As Integer
            Get
                Return Me.devRollupCountField
            End Get
            Set
                Me.devRollupCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TestRollupCount() As Integer
            Get
                Return Me.testRollupCountField
            End Get
            Set
                Me.testRollupCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OtherRollupCount() As Integer
            Get
                Return Me.otherRollupCountField
            End Get
            Set
                Me.otherRollupCountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property IsOpenPosition() As System.Nullable(Of Boolean)
            Get
                Return Me.isOpenPositionField
            End Get
            Set
                Me.isOpenPositionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApprovedInd() As String
            Get
                Return Me.approvedIndField
            End Get
            Set
                Me.approvedIndField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageLink() As String
            Get
                Return Me.imageLinkField
            End Get
            Set
                Me.imageLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonLink() As String
            Get
                Return Me.personLinkField
            End Get
            Set
                Me.personLinkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrganizationLink() As String
            Get
                Return Me.organizationLinkField
            End Get
            Set
                Me.organizationLinkField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://who/")>  _
    Partial Public Class DirectsChain
        
        Private managerField As DirectData
        
        Private directsField() As DirectData
        
        '''<remarks/>
        Public Property Manager() As DirectData
            Get
                Return Me.managerField
            End Get
            Set
                Me.managerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Directs() As DirectData()
            Get
                Return Me.directsField
            End Get
            Set
                Me.directsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(PersonContextWithPeers)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://who/")>  _
    Partial Public Class PersonContext
        
        Private personField As Person
        
        Private managersField() As Person
        
        Private directsChainsField() As DirectsChain
        
        '''<remarks/>
        Public Property Person() As Person
            Get
                Return Me.personField
            End Get
            Set
                Me.personField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Managers() As Person()
            Get
                Return Me.managersField
            End Get
            Set
                Me.managersField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DirectsChains() As DirectsChain()
            Get
                Return Me.directsChainsField
            End Get
            Set
                Me.directsChainsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://who/")>  _
    Partial Public Class PersonContextWithPeers
        Inherits PersonContext
        
        Private peersField() As DirectData
        
        '''<remarks/>
        Public Property Peers() As DirectData()
            Get
                Return Me.peersField
            End Get
            Set
                Me.peersField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPeopleByQueryCompletedEventHandler(ByVal sender As Object, ByVal e As FindPeopleByQueryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPeopleByQueryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Person()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Person())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPeopleByFuzzyCompletedEventHandler(ByVal sender As Object, ByVal e As FindPeopleByFuzzyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPeopleByFuzzyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Person()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Person())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPersonByAliasCompletedEventHandler(ByVal sender As Object, ByVal e As FindPersonByAliasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPersonByAliasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Person
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Person)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPeopleByAliasCompletedEventHandler(ByVal sender As Object, ByVal e As FindPeopleByAliasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPeopleByAliasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Person()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Person())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPeopleByEmployeeIdCompletedEventHandler(ByVal sender As Object, ByVal e As FindPeopleByEmployeeIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPeopleByEmployeeIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Person()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Person())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPersonContextWithPeersCompletedEventHandler(ByVal sender As Object, ByVal e As FindPersonContextWithPeersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPersonContextWithPeersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PersonContextWithPeers
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PersonContextWithPeers)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub FindPersonContextByAliasCompletedEventHandler(ByVal sender As Object, ByVal e As FindPersonContextByAliasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FindPersonContextByAliasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PersonContext
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PersonContext)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetTagCompletionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetTagCompletionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTagCompletionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetUnderCompletedEventHandler(ByVal sender As Object, ByVal e As GetUnderCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUnderCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Person()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Person())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetSearchCompletionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetSearchCompletionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSearchCompletionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetSearchCompletionsByAliasCompletedEventHandler(ByVal sender As Object, ByVal e As GetSearchCompletionsByAliasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSearchCompletionsByAliasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub GetSearchAddinCompletionsCompletedEventHandler(ByVal sender As Object, ByVal e As GetSearchAddinCompletionsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSearchAddinCompletionsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SearchSuggestion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SearchSuggestion)
            End Get
        End Property
    End Class
End Namespace
